# Generated by Django 5.1.1 on 2025-03-31 06:49

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_profile_picture_alter_program_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.program'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default=accounts.models.default_profile_picture, null=True, upload_to='profile_pics/'),
        ),
    ]
