# Generated by Django 5.1.1 on 2025-03-31 16:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_group_program_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(related_name='courses', to='accounts.program'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default=accounts.models.default_profile_picture, null=True, upload_to='profile_pics/'),
        ),
    ]
