# Generated by Django 5.1.1 on 2025-04-01 01:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_course_programs_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default=accounts.models.default_profile_picture, null=True, upload_to='profile_pics/'),
        ),
    ]
